2020-06-28T19:30:37,303 Non-user install because site-packages writeable
2020-06-28T19:30:37,312 Created temporary directory: C:\Users\dabyg\AppData\Local\Temp\pip-ephem-wheel-cache-rq4xwc4q
2020-06-28T19:30:37,312 Created temporary directory: C:\Users\dabyg\AppData\Local\Temp\pip-req-tracker-218k8d8i
2020-06-28T19:30:37,312 Initialized build tracking at C:\Users\dabyg\AppData\Local\Temp\pip-req-tracker-218k8d8i
2020-06-28T19:30:37,313 Created build tracker: C:\Users\dabyg\AppData\Local\Temp\pip-req-tracker-218k8d8i
2020-06-28T19:30:37,313 Entered build tracker: C:\Users\dabyg\AppData\Local\Temp\pip-req-tracker-218k8d8i
2020-06-28T19:30:37,313 Created temporary directory: C:\Users\dabyg\AppData\Local\Temp\pip-install-jtvnj5k_
2020-06-28T19:30:37,314 ERROR: Invalid requirement: '$'
2020-06-28T19:30:37,314 Exception information:
2020-06-28T19:30:37,314 Traceback (most recent call last):
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_vendor\packaging\requirements.py", line 98, in __init__
2020-06-28T19:30:37,314     req = REQUIREMENT.parseString(requirement_string)
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_vendor\pyparsing.py", line 1955, in parseString
2020-06-28T19:30:37,314     raise exc
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_vendor\pyparsing.py", line 3250, in parseImpl
2020-06-28T19:30:37,314     raise ParseException(instring, loc, self.errmsg, self)
2020-06-28T19:30:37,314 pip._vendor.pyparsing.ParseException: Expected W:(abcd...), found '$'  (at char 0), (line:1, col:1)
2020-06-28T19:30:37,314 
2020-06-28T19:30:37,314 During handling of the above exception, another exception occurred:
2020-06-28T19:30:37,314 
2020-06-28T19:30:37,314 Traceback (most recent call last):
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_internal\req\constructors.py", line 358, in parse_req_from_line
2020-06-28T19:30:37,314     req = Requirement(req_as_string)
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_vendor\packaging\requirements.py", line 100, in __init__
2020-06-28T19:30:37,314     raise InvalidRequirement(
2020-06-28T19:30:37,314 pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'$'": Expected W:(abcd...)
2020-06-28T19:30:37,314 
2020-06-28T19:30:37,314 During handling of the above exception, another exception occurred:
2020-06-28T19:30:37,314 
2020-06-28T19:30:37,314 Traceback (most recent call last):
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in _main
2020-06-28T19:30:37,314     status = self.run(options, args)
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 185, in wrapper
2020-06-28T19:30:37,314     return func(self, options, args)
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_internal\commands\install.py", line 300, in run
2020-06-28T19:30:37,314     reqs = self.get_requirements(
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 321, in get_requirements
2020-06-28T19:30:37,314     req_to_add = install_req_from_line(
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_internal\req\constructors.py", line 396, in install_req_from_line
2020-06-28T19:30:37,314     parts = parse_req_from_line(name, line_source)
2020-06-28T19:30:37,314   File "c:\python38\lib\site-packages\pip\_internal\req\constructors.py", line 373, in parse_req_from_line
2020-06-28T19:30:37,314     raise InstallationError(msg)
2020-06-28T19:30:37,314 pip._internal.exceptions.InstallationError: Invalid requirement: '$'
2020-06-28T19:30:37,355 Removed build tracker: 'C:\\Users\\dabyg\\AppData\\Local\\Temp\\pip-req-tracker-218k8d8i'
